name: CI

on: [push, pull_request]

jobs:
  ci:
    name: OTP ${{ matrix.otp-version }} / Elixir ${{ matrix.elixir-version }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # https://hexdocs.pm/elixir/compatibility-and-deprecations.html
        include:
          - elixir-version: "1.18"
            otp-version: "27"
          - elixir-version: "1.18"
            otp-version: "26"
          - elixir-version: "1.18"
            otp-version: "25"
          - elixir-version: "1.17"
            otp-version: "27"
          - elixir-version: "1.17"
            otp-version: "26"
          - elixir-version: "1.17"
            otp-version: "25"
          - elixir-version: "1.16"
            otp-version: "26"
          - elixir-version: "1.16"
            otp-version: "25"
          - elixir-version: "1.15"
            otp-version: "26"
          - elixir-version: "1.15"
            otp-version: "25"
          - elixir-version: "1.14"
            otp-version: "25"
          - elixir-version: "1.13"
            otp-version: "24"
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp-version }}
          elixir-version: ${{ matrix.elixir-version }}
      - run: make dependencies
      - run: make lint
      - run: make test
      - run: mix coveralls.github --parallel --flagname otp-${{ matrix.otp-version }}-elixir-${{ matrix.elixir-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: mix hex.publish --dry-run
        env:
          HEX_API_KEY: DRYRUN
