name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:
    # Ubuntu 20.04, Erlang/OTP 20-25
    # https://github.com/erlef/setup-beam
    name: Erlang ${{matrix.otp-version}} / Elixir ${{matrix.elixir-version}}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # https://hexdocs.pm/elixir/compatibility-and-deprecations.html
        elixir-version: [1.14.x, 1.13.x, 1.12.x, 1.11.x, 1.10.x, 1.9.x, 1.8.x]
        include:
          - elixir-version: 1.14.x
            otp-version: 25.x
          - elixir-version: 1.13.x
            otp-version: 24.x
          - elixir-version: 1.12.x
            otp-version: 24.x
          - elixir-version: 1.11.x
            otp-version: 23.x
          - elixir-version: 1.10.x
            otp-version: 22.x
          - elixir-version: 1.9.x
            otp-version: 21.x
          - elixir-version: 1.8.x
            otp-version: 20.x
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp-version }}
          elixir-version: ${{ matrix.elixir-version }}
      - run: make dependencies
      - run: make lint
      - run: make test
      - run: mix coveralls.github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: mix hex.publish --dry-run
        env:
          HEX_API_KEY: DRYRUN
